name: Package Release Publish

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_body:
        description: 'Release notes/body (leave blank to use default template)'
        required: false
        default: ''

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse_version.outputs.version }}
      package_path: ${{ steps.package_release.outputs.package_path }}
    steps:
      - uses: actions/checkout@v4

      - name: Parse TOC version number
        id: parse_version
        run: |
          VERSION=$(grep -E '^## Version:' Labormate.toc | sed -E 's/## Version:[[:space:]]*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.parse_version.outputs.version }}
          git push origin ${{ steps.parse_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package release
        id: package_release
        run: |
          mkdir -p release/Labormate
          cp *.lua *.toc *.xml release/Labormate/
          cp -r assets/ release/Labormate/assets/
          zip -r Labormate-${{ steps.parse_version.outputs.version }}.zip release/Labormate/
          echo "package_path="Labormate-${{ steps.parse_version.outputs.version }}.zip" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.package.outputs.version }}
          release_name: ${{ needs.package.outputs.version }}
          body: |
            Stuff goes here
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.package.outputs.package_path }}
          asset_name: Labormate-${{ needs.package.outputs.version }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
